ARG REPOSITORY_URL
ARG REPOSITORY_NAMESPACE
FROM ${REPOSITORY_URL}/${REPOSITORY_NAMESPACE}/openjdk:17-jdk-slim
WORKDIR /app

ARG PROJECT_VERSION
COPY target/backend-boot-template-${PROJECT_VERSION}-SNAPSHOT.jar app.jar


# 容器启动时运行的命令
ENTRYPOINT ["java", "-jar", "/app/app.jar"]

# 暴露容器的端口
ARG PROJECT_PORT
EXPOSE ${PROJECT_PORT}