spring:
  profiles:
    active: @active@
  application:
    name: backend-boot-template
  main:
    # 是否允许循环依赖，并且依靠三级缓存解决循环依赖问题
    allow-circular-references: true
  flyway:
    # 是否启用flyway
    enabled: true
    # 编码格式，默认UTF-8
    encoding: UTF-8
    # 迁移sql脚本文件存放路径，默认db/migration
    locations: classpath:db/migration
    # 迁移sql脚本文件名称的前缀，默认V
    sql-migration-prefix: V
    # 迁移sql脚本文件名称的分隔符，默认2个下划线__
    sql-migration-separator: __
    # 迁移sql脚本文件名称的后缀
    sql-migration-suffixes: .sql
    # 迁移时是否进行校验，默认true
    validate-on-migrate: true
    # 当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'backend-boot-template'
      paths-to-match: '/**'
      packages-to-scan: org.visage.backend.controller
  default-flat-param-object: false

# 配置健康检查
management:
  endpoint:
    health:
      probes:
        enabled: true  # 启用 Kubernetes 探针支持
  endpoints:
    web:
      exposure:
        include: health  # 暴露健康检查端点