server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json

spring:
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: localhost:8848,localhost:8858
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/backend_center?serverTimezone=GMT%2B8&useLegacyDatetimeCode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    username: root
    password: zxj201328
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: zxj201328
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 8 # 连接池中的最大空闲连接
