server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend-boot-template?serverTimezone=GMT%2B8&useLegacyDatetimeCode=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: localhost:8848
        username: nacos
        password: nacos