spring:
  profiles:
    active: @active@
  application:
    name: backend-boot-template
  main:
    # 是否允许循环依赖，并且依靠三级缓存解决循环依赖问题
    allow-circular-references: true

springdoc:
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'backend-boot-template'
      paths-to-match: '/**'
      packages-to-scan: org.visage.backend.controller
  default-flat-param-object: false

# 配置健康检查
management:
  endpoint:
    health:
      probes:
        enabled: true  # 启用 Kubernetes 探针支持
  endpoints:
    web:
      exposure:
        include: health  # 暴露健康检查端点